#########################################################################
# Title:         Saltbox: Rclone - Build URL Tasks                      #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Build URL | Install common packages
  ansible.builtin.apt:
    state: latest
    name:
      - curl
      - jq

- name: Build URL | Check if rclone version was specified
  ansible.builtin.set_fact:
    rclone_version_is_specified: "{{ not ((rclone is undefined)
                                     or
                                     (rclone is none)
                                     or
                                     (rclone | trim | length == 0)
                                     or
                                     (rclone.version is undefined)
                                     or
                                     (rclone.version is none)
                                     or
                                     (rclone.version | trim | length == 0)) }}"

- name: Build URL | Display rclone version specified
  ansible.builtin.debug:
    msg: "Rclone version specified: {{ rclone.version }}"
  when: rclone_version_is_specified

- name: Build URL | Set vars for current version
  ansible.builtin.set_fact:
    rclone_version_specified: "latest"
    rclone_download_url: "https://downloads.rclone.org/rclone-current-linux-amd64.zip"
  when: (not rclone_version_is_specified) or (rclone.version in ['latest', 'current'])

- name: "Get URL for latest rclone release"
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/git/github_api_request.yml"
  vars:
    github_api_url: "{{ rclone_latest_releases_url }}"
    github_api_result_var: rclone_latest_release_api
  when: (not rclone_version_is_specified) or (rclone.version in ['latest', 'current'])

- name: "Resolve URL for latest rclone release"
  ansible.builtin.set_fact:
    rclone_latest_download_url: "{{ ((rclone_latest_release_api.content | from_json).assets
                                  | selectattr('name', 'search', 'linux-amd64.zip')
                                  | map(attribute='browser_download_url')
                                  | first) }}"
  changed_when: false
  when: (not rclone_version_is_specified) or (rclone.version in ['latest', 'current'])

- name: Build URL | Set vars for beta version
  ansible.builtin.set_fact:
    rclone_version_specified: "{{ rclone.version }}"
    rclone_download_url: "https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip"
  when: rclone_version_is_specified and (rclone.version == 'beta')

- name: Build URL | Specified version tasks
  when:
    - rclone_version_is_specified
    - not (rclone.version in ['beta', 'latest', 'current'])
  block:
    - name: Build URL | Set temp 'rclone_version_specified0' var for specified version
      ansible.builtin.set_fact:
        rclone_version_specified0: >-
          {{ ('%.2f' | format(rclone.version | float))
          if ((rclone.version | type_debug == 'float') or (rclone.version | type_debug == 'int'))
          else (rclone.version | regex_replace('(^v\\.|^v)', '')) }}

    - name: Build URL | Check if specified version is available
      ansible.builtin.include_tasks: "{{ resources_tasks_path }}/git/github_api_request.yml"
      vars:
        github_api_url: "https://api.github.com/repos/ncw/rclone/git/refs/tags"
        github_api_result_var: rclone_tags_api

    - name: Build URL | Resolve specified version availability
      ansible.builtin.set_fact:
        rclone_version_specified0_check:
          stdout: "{{ ((rclone_tags_api.content | from_json)
                      | map(attribute='ref')
                      | map('regex_replace', '^refs/tags/v', '')
                      | select('equalto', rclone_version_specified0)
                      | join('')) }}"
      changed_when: false

    - name: Build URL | Set vars for specified version if available
      ansible.builtin.set_fact:
        rclone_version_specified: "{{ rclone_version_specified0 }}"
        rclone_download_url: 'https://downloads.rclone.org/v{{ rclone_version_specified0 }}/rclone-v{{ rclone_version_specified0 }}-linux-amd64.zip'
      when: (rclone_version_specified0_check.stdout | trim | length > 0)

    - name: Build URL | Display message if specified version is not available
      ansible.builtin.debug:
        msg: "Rclone version {{ rclone_version_specified0 }} is not available. Installing the latest available version instead..."
      when: (rclone_version_specified0_check.stdout | trim | length == 0)

    - name: Build URL | Set vars for specified version if not available
      ansible.builtin.set_fact:
        rclone_version_specified: "latest"
        rclone_download_url: "https://downloads.rclone.org/rclone-current-linux-amd64.zip"
      when: (rclone_version_specified0_check.stdout | trim | length == 0)
