#########################################################################
# Title:         Saltbox: ctop | Default Variables                      #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
ctop_releases_url: "https://api.github.com/repos/bcicen/ctop/releases/latest"

ctop_binary_path: /usr/local/bin/ctop

ctop_binary_version_lookup_command: |
  {{ ctop_binary_path }} -v | head -n 1 | awk '{ print $3 }' | sed 's/,$//'
