#########################################################################
# Title:         Saltbox: ctop Role                                     #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Get latest ctop URL
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/git/github_api_request.yml"
  vars:
    github_api_url: "{{ ctop_releases_url }}"
    github_api_result_var: ctop_release_api

- name: Resolve ctop download URL
  ansible.builtin.set_fact:
    ctop_download_url_lookup: "{{ ((ctop_release_api.content | from_json).assets
                                  | selectattr('name', 'search', 'linux-amd64')
                                  | map(attribute='browser_download_url')
                                  | first) }}"
  changed_when: false

- name: Install ctop
  ansible.builtin.get_url:
    url: "{{ ctop_download_url_lookup }}"
    dest: "{{ ctop_binary_path }}"
    mode: "0775"
    owner: root
    group: root
    force: true
    validate_certs: false
  ignore_errors: true
  register: ctop_download_status
  until: "ctop_download_status is not failed"
  retries: "{{ ansible_retry_count
            if (not continuous_integration)
            else ansible_retry_count_ci }}"
  delay: 10

- name: Tasks to do when ctop download is successful
  when: (ctop_download_status is succeeded)
  block:
    - name: Get ctop binary version
      ansible.builtin.shell: "{{ ctop_binary_version_lookup_command }}"
      register: ctop_binary_version
      ignore_errors: true

    - name: Display ctop binary version
      ansible.builtin.debug:
        msg: "ctop {{ ctop_binary_version.stdout }} installed."
