#########################################################################
# Title:         Saltbox: btop Role                                     #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "btop | Get URL for latest btop release"
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/git/github_api_request.yml"
  vars:
    github_api_url: "{{ btop_releases_url }}"
    github_api_result_var: btop_release_api

- name: "btop | Resolve btop download URL"
  ansible.builtin.set_fact:
    btop_download_url: "{{ ((btop_release_api.content | from_json).assets
                           | selectattr('name', 'search', 'btop-x86_64-(unknown-)?linux-musl.tbz')
                           | map(attribute='browser_download_url')
                           | first) }}"
  changed_when: false

- name: "btop | Create directories"
  ansible.builtin.file:
    path: "/tmp/btop"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"

- name: "btop | Download btop"
  ansible.builtin.get_url:
    url: "{{ btop_version_lock_url if btop_version_lock else btop_download_url }}"
    dest: "/tmp/btop"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
  register: x
  until: "x is not failed"
  retries: "{{ ansible_retry_count
            if (not continuous_integration)
            else ansible_retry_count_ci }}"
  delay: 10

- name: "btop | Unpack btop"
  ansible.builtin.shell: "tar -xjf btop-x86_64-*linux-musl.tbz"
  args:
    chdir: "/tmp/btop"

- name: "btop | Ensure executable bit on install.sh"
  ansible.builtin.file:
    path: "/tmp/btop/btop/install.sh"
    mode: "0755"

- name: "btop | Install btop"
  ansible.builtin.shell: "bash /tmp/btop/btop/install.sh"
  args:
    chdir: "/tmp/btop/btop"
  become: true
  become_user: "{{ user.name }}"

- name: "btop | Remove temp folder"
  ansible.builtin.file:
    path: "/tmp/btop"
    state: absent
